// SPDX-License-Identifier: MIT OR Apache-2.0

use iced::keyboard;
use iced::window;

use crate::connection;

use super::model::{ProtocolMode, SettingsTabKind, SettingsTextKey, SettingsToggleKey};

#[derive(Debug, Clone)]
pub enum Message {
    TabSelected(usize),
    CloseTab(usize),
    NewSshTab,
    TerminalInput(Vec<u8>),
    ImePreedit(String),
    ImeCommit(String),
    FontLoaded(Result<(), iced::font::Error>),
    ConnectionMessage(u64, connection::ConnectionEvent),
    TerminalResize(usize, usize),
    TerminalScroll(f32),
    TerminalScrollTo(usize),
    HostChanged(String),
    PortChanged(String),
    UserChanged(String),
    PassChanged(String),
    SerialPortChanged(String),
    SerialBaudChanged(String),
    RdpHostChanged(String),
    RdpPortChanged(String),
    RdpUserChanged(String),
    RdpPassChanged(String),
    RdpResolutionSelected(usize),
    VncHostChanged(String),
    VncPortChanged(String),
    VncPassChanged(String),
    SelectProtocol(ProtocolMode),
    SelectLocalShell(usize),
    ConnectSsh,
    ConnectTelnet,
    ConnectLocal,
    ConnectSerial,
    ConnectRdp,
    ConnectVnc,
    TabPressed(bool),
    FieldFocused(usize),
    WindowIdCaptured(window::Id),
    WindowDrag,
    WindowResize(window::Direction),
    ResizeFinished,
    MinimizeWindow,
    MaximizeWindow,
    CloseWindow,
    ToggleMenu(&'static str),
    CloseMenuDeferred,
    CloseMenu,
    OpenProtocolTab(ProtocolMode),
    SelectionStart(usize, usize),
    SelectionUpdate(usize, usize),
    CopyText(String),
    CopyCurrentSelection,
    PasteFromClipboard,
    PasteData(Option<String>),
    ClearSelection,
    TryHandleKey(keyboard::Key, keyboard::Modifiers),
    RemoteDisplayInput(connection::RemoteInput),
    RemoteDisplayInputs(Vec<connection::RemoteInput>),
    RemoteSecureAttention(bool),
    SyncRemoteKeyboardIndicators,
    ReleaseRemoteModifiers,
    WindowSizeChanged(f32, f32),
    RemoteDisplayRedrawPulse,
    OpenSettingsTab(SettingsTabKind),
    SettingsCategorySelected(usize),
    ToggleSettingsCheckbox(SettingsToggleKey),
    SettingsTextChanged(SettingsTextKey, String),
}
